# Generated by Django 4.1.5 on 2023-03-11 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('all_limit', models.IntegerField()),
                ('transportation_cost', models.DecimalField(decimal_places=2, default=0.01, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StockGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(default=0, null=True)),
                ('limit', models.PositiveIntegerField(blank=True, null=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement_of_goods.good')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement_of_goods.stock')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='goods',
            field=models.ManyToManyField(through='placement_of_goods.StockGood', to='placement_of_goods.good'),
        ),
    ]
