# Generated by Django 4.1.5 on 2023-03-11 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placement_of_goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='stockgood',
            name='limit',
        ),
        migrations.AddField(
            model_name='stockgood',
            name='amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockgood',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClientGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement_of_goods.client')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement_of_goods.good')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='goods',
            field=models.ManyToManyField(through='placement_of_goods.ClientGood', to='placement_of_goods.good'),
        ),
    ]
